Default:
    shape: box
    color: '#FFFFFF'
    style: filled
    border: 0
    cellborder: 0
    display_type_title: True
    value: 10

AstroqueryModule:
    shape: ellipse
    color: '#00CC00'
    style: filled
    value: 50

AstrophysicalObject:
    shape: ellipse
    color: '#6262be'
    style: filled
    value: 50

AstrophysicalRegion:
    shape: ellipse
    color: '#6262bf'
    style: filled
    value: 50

AstrophysicalImage:
    shape: ellipse
    color: '#027F45'
    style: filled
    value: 50

CommandParameter:
    shape: box
    color: '#6262be'
    style: filled

CommandOutput:
    shape: box
    color: '#FFFF00'
    style: filled

CommandOutputNotebook:
    shape: box
    color: '#DBA3BC'
    style: filled

CommandOutputImage:
    shape: box
    color: '#FFFFFF'
    style: filled
    border: 1

CommandOutputFitsFile:
    shape: box
    color: '#FFFFFF'
    style: filled
    border: 1

CommandOutputEcsvFile:
    shape: box
    color: '#FFFFFF'
    style: filled
    border: 1

CommandInput:
    shape: box
    color: '#DBA3BC'
    style: filled
    display_type_title: False

Action:
    shape: diamond
    color: '#D5C15D'
    style: filled
    display_type_title: False
    value: 400

Angle:
    shape: box
    color: '#1B81FB'
    style: filled

SkyCoordinates:
    shape: box
    color: '#1B81FB'
    style: filled

Coordinates:
    shape: box
    color: '#1B81FB'
    style: filled

Position:
    shape: box
    color: '#1B81FB'
    style: filled

Pixels:
    shape: box
    color: '#1B81FB'
    style: filled